export type SubCategoryItems = {
    [key: string]: string[];
};

export const subCategoryItems: SubCategoryItems = {
    'Logo Design': ['New Logo', 'Logo Update'],
    'Marketing Materials': ['Brochures', 'Flyers'],
    'Newsletter': ['Monthly Newsletter', 'Special Announcements'],
    'Intranet': ['Intranet Updates', 'Content Management'],
    'Job Posting': ['Full-Time Positions', 'Internships'],
    'Interviews': ['Technical Interviews', 'HR Interviews'],
    'Application Error': ['Crash Report', 'Bug Report'],
    'Software Installation': ['New Installation', 'Reinstallation'],
    'PC Issues': ['Blue Screen', 'Slow Performance'],
    'Printer Issues': ['Paper Jam', 'Toner Replacement'],
    'Budgeting': ['Quarterly Budget', 'Annual Budget'],
    'Payroll': ['Salary Processing', 'Deductions'],
    'Asset Tracking': ['Barcode Tags', 'RFID Tags'],
    'Asset Disposal': ['E-Waste', 'Physical Disposal'],
    'Policy Review': ['New Policy', 'Policy Update'],
    'Regulatory Compliance': ['GDPR', 'SOX Compliance'],
    'Risk Analysis': ['Financial Risks', 'Operational Risks'],
    'Risk Mitigation': ['Risk Transfer', 'Risk Reduction'],
    'Purchase Orders': ['New Order', 'Order Follow-Up'],
    'Supplier Inquiries': ['Product Availability', 'Delivery Time'],
    'Contract Negotiation': ['Price Negotiation', 'Terms & Conditions'],
    'Vendor Payments': ['Invoice Processing', 'Payment Follow-Up'],
    'Badge Issuance': ['New Badge', 'Replacement Badge'],
    'Entry Logs': ['Log Review', 'Log Archiving'],
    'Security Breach': ['Report Incident', 'Breach Analysis'],
    'Unauthorized Access': ['Incident Report', 'Lockdown Procedures'],
    'Domestic Flights': ['One-Way', 'Round-Trip'],
    'International Flights': ['One-Way', 'Round-Trip'],
    'Hotel Booking': ['Local Hotels', 'International Hotels'],
    'Rental Cars': ['Sedans', 'SUVs'],
};
